// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxjnsxmrvmpvvwznyiac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4am5zeG1ydm1wdnZ3em55aWFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDE4ODcsImV4cCI6MjA1OTUxNzg4N30.zIjB8nTYBv_MAs3jKucYVs5PqyQesoLImX7HgymZwRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);